name: Tokate
on:
  issue_comment:
    types: [created]
  pull_request_target:
    types: [opened, reopened, synchronize, edited, ready_for_review, converted_to_draft, labeled, unlabeled, assigned, unassigned]
permissions: {}
jobs:
  coordinate:
    permissions:
      contents: write
      issues: read
      pull-requests: write
    uses: obselate/tokate/.github/workflows/tokate-shared.yml@646d3329596f9f29f64d5387f30d4fe11548626d
    with:
      archive_url: 'https://api.github.com/repos/obselate/tokate/releases/assets/620771201'
      archive_sha256: '009b1bf1b844f09ea63cd215f647c8c5efdcf6c02ad97a4d0408c1182d1e5c0a'
      member: 'tokate-0.2.82-linux-x64/tokate'
