name: Tokate
on:
  issue_comment:
    types: [created]
  pull_request_target:
    types: [opened, reopened, synchronize, edited, ready_for_review, converted_to_draft, labeled, unlabeled, assigned, unassigned]
permissions: {}
jobs:
  coordinate:
    permissions:
      contents: write
      issues: read
      pull-requests: write
    uses: obselate/tokate/.github/workflows/tokate-shared.yml@15aa6152df315b7efebfb1ca5e1e263c568c5d26
    with:
      archive_url: 'https://api.github.com/repos/obselate/tokate/releases/assets/621412175'
      archive_sha256: '3524e9026945ca43cfd802e507cb335f86482f440e42fa75e339f2cbcf167a5f'
      member: 'tokate-0.2.93-linux-x64/tokate'
