name: Tokate
on:
  issue_comment:
    types: [created]
  pull_request_target:
    types: [opened, reopened, synchronize, edited, ready_for_review, converted_to_draft, labeled, unlabeled, assigned, unassigned]
permissions: {}
jobs:
  coordinate:
    permissions:
      contents: write
      issues: read
      pull-requests: write
    uses: obselate/tokate/.github/workflows/tokate-shared.yml@a6dc917c5deedf7fc7195a2aa1c1acfd4ecaa107
    with:
      archive_url: 'https://api.github.com/repos/obselate/tokate/releases/assets/624852350'
      archive_sha256: '278a0701fb87d27c34c4810aac9927f0ab0fe5dc1f9567ef8d0da7d85ceb564e'
      member: 'tokate-0.3.4-linux-x64/tokate'
